name:                stenome
version:             0.1.0.0
github:              "d3zd3z/stenome"
license:             BSD3
author:              "David Brown"
maintainer:          "davidb@davidb.org"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/stenome#readme>

dependencies:
- aeson >= 1.2 && < 1.3
- array >= 0.5 && < 0.6
- base >= 4.7 && < 5
- bytestring > 0.10 && < 0.11
- convertible >= 1.1 && < 1.2
- HDBC >= 2.4 && < 2.5
- HDBC-sqlite3 >= 2.3 && < 2.4
- random >= 1.1 && < 1.2
- time >= 1.8 && < 1.9

library:
  source-dirs: src

executables:
  stenome-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - stenome

tests:
  stenome-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - stenome
